//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onlineshopping.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class carstatu
    {
        public int carstatusid { get; set; }
        public string carstatus { get; set; }
    }
}
