//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onlineshopping.Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyonlineshopEntities : DbContext
    {
        public MyonlineshopEntities()
            : base("name=MyonlineshopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<carstatu> carstatus { get; set; }
        public virtual DbSet<cart> carts { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<memberRole> memberRoles { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<shippingdetail> shippingdetails { get; set; }
        public virtual DbSet<slideImage> slideImages { get; set; }
        public virtual DbSet<product> products { get; set; }
       
    }
}
